"""Phase F2: node scoring priors.

`prior_category` is a fact about the code; `prior` (the numeric multiplier)
is a tunable parameter resolved from config/node_priors.yaml at scoring
time (Phase F3) -- same split as edge_weights.py's kind/weight.

Two of the six categories need different timing:

- `config`/`migration`/`generated`/`barrel` are file-local facts (path,
  content, symbol count) -- classified once at parse time, in ingest.py,
  same as CodeImport.kind. `prior_source` for these is "pattern" (filename/
  path match) or "structural" (barrel -- a structural fact about the file's
  own content, not just its name).

- `entry` depends on fan_in, which only exists once the whole repo's graph
  is built (ranking.py, after parsing) -- and can go stale without this
  file itself changing (a new importer elsewhere flips it). So entry
  detection is NOT done here at parse time at all: files default to
  category "source", prior_source "graph", and ranking.py's write-back
  (see rank_repo) is the only thing that ever promotes "source" to "entry"
  or demotes it back. That write-back only ever touches prior_source ==
  "graph" rows -- once E4 lands and makes entry detection a parse-time
  structural fact (like the others), those rows get prior_source =
  "structural" and the write-back leaves them alone from then on.
"""
import fnmatch
import re
from pathlib import Path
from typing import Optional

import yaml

ALL_CATEGORIES = ("entry", "source", "barrel", "config", "migration", "generated")

# Categories the UI's "hide config/migration/generated" control removes. Named
# here rather than inline at the endpoint because it is the same set the
# frontend hard-codes as NOISE_CATEGORIES in lib/filters.ts, and the two must
# agree: the graph endpoint filters files server-side using THIS list while the
# reading list filters the same files client-side using that one, so a
# divergence would make the two views disagree about which files exist while
# both looked correct.
#
# Cross-language, so it cannot be shared as code. What IS enforced here is that
# every member is a real category (test_node_priors) -- a typo would otherwise
# silently filter nothing.
NOISE_CATEGORIES = ("config", "migration", "generated")

DEFAULT_PRIOR_VALUES = {
    "entry": 1.4, "source": 1.0, "barrel": 0.4, "config": 0.2, "migration": 0.15, "generated": 0.05,
}
DEFAULT_CONFIG_FILENAME_PATTERNS = ["*.config.*", "alembic.ini", "setup.py"]
DEFAULT_MIGRATION_PATH_MARKERS = ["alembic/versions/"]
DEFAULT_GENERATED_FILENAME_SUFFIXES = ["_pb2.py"]
DEFAULT_GENERATED_HEADER_MARKERS = ["@generated", "DO NOT EDIT", "This file is automatically generated", "Code generated by"]
DEFAULT_GENERATED_LOCKFILE_NAMES = ["package-lock.json", "yarn.lock", "poetry.lock"]

_HEADER_SCAN_LINES = 10


def _priors_path() -> Path:
    from app.core.config import BACKEND_DIR, settings
    p = Path(settings.NODE_PRIORS_PATH)
    return p if p.is_absolute() else BACKEND_DIR / p


def load_node_priors() -> dict:
    """Full config dict (prior_values + every pattern list), read fresh every
    call. A missing or unreadable file falls back to the defaults above."""
    path = _priors_path()
    defaults = {
        "prior_values": dict(DEFAULT_PRIOR_VALUES),
        "config_filename_patterns": list(DEFAULT_CONFIG_FILENAME_PATTERNS),
        "migration_path_markers": list(DEFAULT_MIGRATION_PATH_MARKERS),
        "generated_filename_suffixes": list(DEFAULT_GENERATED_FILENAME_SUFFIXES),
        "generated_header_markers": list(DEFAULT_GENERATED_HEADER_MARKERS),
        "generated_lockfile_names": list(DEFAULT_GENERATED_LOCKFILE_NAMES),
    }
    if not path.is_file():
        return defaults
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    merged = dict(defaults)
    for key in defaults:
        if key in data:
            merged[key] = data[key] if key != "prior_values" else {**defaults["prior_values"], **(data[key] or {})}
    return merged


def resolve_prior(category: str, priors: Optional[dict] = None) -> float:
    priors = priors if priors is not None else load_node_priors()
    values = priors.get("prior_values", DEFAULT_PRIOR_VALUES)
    return values.get(category, DEFAULT_PRIOR_VALUES.get(category, 1.0))


def _is_trivial_init(source_text: str) -> bool:
    """Heuristic for a barrel-like __init__.py: after stripping a leading
    module docstring (if present) and any `__all__ = [...]` assignment
    (single- or multi-line), nothing but blank lines/comments remains.
    Text-based, not AST-based -- deliberately simple; a false positive here
    just mislabels a near-empty file as `barrel` instead of `source`, which
    barely affects ranking either way."""
    text = source_text.strip()
    text = re.sub(r'^("""|\'\'\')(.*?)(\1)', "", text, count=1, flags=re.DOTALL).strip()
    text = re.sub(r"^__all__\s*=\s*\[[^\]]*\]", "", text, flags=re.DOTALL).strip()
    remaining = [ln for ln in text.splitlines() if ln.strip() and not ln.strip().startswith("#")]
    return len(remaining) == 0


def classify_file_local_category(
    *, path: str, source_text: str, symbol_count: int, reexport_count: int, priors: Optional[dict] = None,
) -> tuple:
    """Returns (category, prior_source). Never returns "entry" -- that's
    graph-dependent and handled only by ranking.py's write-back. Checked in
    this order; first match wins: config, migration, generated, barrel,
    else "source".

    barrel requires an actual FORWARD (a re-export edge, reexport_count >= 1)
    or a trivial __init__.py -- not merely "has at least one import". A
    plain script that imports a helper and calls it, defining nothing else,
    has symbol_count == 0 too, but it is a script, not a pass-through file;
    counting bare import presence would permanently block it from ever
    being eligible for "entry" (barrel's prior_source is "structural",
    never touched by ranking's write-back). Caught by a real test before
    this shipped, not assumed away."""
    priors = priors if priors is not None else load_node_priors()
    basename = Path(path).name

    if any(fnmatch.fnmatch(basename, pat) for pat in priors["config_filename_patterns"]):
        return "config", "pattern"

    if any(marker in path for marker in priors["migration_path_markers"]):
        return "migration", "pattern"

    if any(basename.endswith(suffix) for suffix in priors["generated_filename_suffixes"]):
        return "generated", "pattern"
    if basename in priors["generated_lockfile_names"]:  # currently unreachable -- see node_priors.yaml
        return "generated", "pattern"
    header = "\n".join(source_text.splitlines()[:_HEADER_SCAN_LINES])
    if any(marker in header for marker in priors["generated_header_markers"]):
        return "generated", "pattern"

    if symbol_count == 0:
        if reexport_count >= 1:
            return "barrel", "structural"
        if basename == "__init__.py" and _is_trivial_init(source_text):
            return "barrel", "structural"

    return "source", "graph"
