"""Phase F2: node prior classification (file-local part only -- the
graph-dependent entry write-back lives in ranking.py and is tested in
test_ranking.py, since it needs a real graph)."""
from app.services.codebase.node_priors import (
    ALL_CATEGORIES,
    _is_trivial_init,
    classify_file_local_category,
    load_node_priors,
    resolve_prior,
)


class TestConfigDetection:
    def test_dotted_config_pattern(self):
        cat, source = classify_file_local_category(
            path="frontend/tailwind.config.js", source_text="module.exports = {}", symbol_count=0, reexport_count=0
        )
        assert (cat, source) == ("config", "pattern")

    def test_alembic_ini(self):
        cat, source = classify_file_local_category(
            path="backend/alembic.ini", source_text="[alembic]\n", symbol_count=0, reexport_count=0
        )
        assert (cat, source) == ("config", "pattern")

    def test_setup_py(self):
        cat, source = classify_file_local_category(
            path="setup.py", source_text="from setuptools import setup\nsetup()\n", symbol_count=0, reexport_count=0
        )
        assert (cat, source) == ("config", "pattern")


class TestMigrationDetection:
    def test_alembic_versions_path(self):
        cat, source = classify_file_local_category(
            path="backend/alembic/versions/abc123_add_thing.py", source_text="def upgrade(): pass\n",
            symbol_count=1, reexport_count=0,
        )
        assert (cat, source) == ("migration", "pattern")


class TestGeneratedDetection:
    def test_pb2_suffix(self):
        cat, source = classify_file_local_category(
            path="proto/thing_pb2.py", source_text="# generated\n", symbol_count=0, reexport_count=0
        )
        assert (cat, source) == ("generated", "pattern")

    def test_header_marker(self):
        cat, source = classify_file_local_category(
            path="app/models_generated.py",
            source_text="# @generated by some-tool\nclass Foo:\n    pass\n",
            symbol_count=1, reexport_count=0,
        )
        assert (cat, source) == ("generated", "pattern")

    def test_header_marker_only_scanned_near_top(self):
        # A marker 50 lines in must not retroactively flag the file --
        # only the first _HEADER_SCAN_LINES lines are checked.
        body = "\n".join([f"x{i} = {i}" for i in range(50)]) + "\n# @generated\n"
        cat, source = classify_file_local_category(
            path="app/thing.py", source_text=body, symbol_count=0, reexport_count=0
        )
        assert cat != "generated"

    def test_lockfile_names_checked_but_unreachable_in_practice(self):
        # Documented as currently unreachable (discovery.py excludes these
        # before they ever become a CodeFile) -- still verified to work if
        # somehow reached.
        cat, source = classify_file_local_category(
            path="frontend/package-lock.json", source_text="{}", symbol_count=0, reexport_count=0
        )
        assert (cat, source) == ("generated", "pattern")


class TestBarrelDetection:
    def test_zero_symbols_with_reexports_is_barrel(self):
        cat, source = classify_file_local_category(
            path="src/index.ts",
            source_text='export { helper } from "./helper";\nexport { other } from "./other";\n',
            symbol_count=0, reexport_count=2,
        )
        assert (cat, source) == ("barrel", "structural")

    def test_script_that_imports_and_calls_but_defines_nothing_is_not_barrel(self):
        # Regression test for a real bug caught by test_ranking.py: a plain
        # script (imports a helper, calls it, defines no functions of its
        # own) has symbol_count == 0, same as a real barrel -- but it's not
        # a pass-through file, and must stay eligible for the "entry" write-
        # back (which only ever touches prior_source == "graph" rows).
        # Blanket "has any import" would have permanently blocked that by
        # mislabeling it prior_source == "structural".
        cat, source = classify_file_local_category(
            path="main.py", source_text="from lib import helper\nhelper()\n",
            symbol_count=0, reexport_count=0,
        )
        assert cat == "source"
        assert source == "graph"

    def test_zero_symbols_zero_reexports_non_init_is_source_not_barrel(self):
        cat, source = classify_file_local_category(
            path="src/empty.ts", source_text="// nothing here\n", symbol_count=0, reexport_count=0
        )
        assert cat == "source"

    def test_docstring_only_init_is_barrel(self):
        assert _is_trivial_init('"""Package docstring."""\n')
        cat, source = classify_file_local_category(
            path="pkg/__init__.py", source_text='"""Package docstring."""\n', symbol_count=0, reexport_count=0
        )
        assert (cat, source) == ("barrel", "structural")

    def test_dunder_all_only_init_is_barrel(self):
        text = '__all__ = ["Foo", "Bar"]\n'
        assert _is_trivial_init(text)
        cat, source = classify_file_local_category(path="pkg/__init__.py", source_text=text, symbol_count=0, reexport_count=0)
        assert (cat, source) == ("barrel", "structural")

    def test_docstring_and_dunder_all_init_is_barrel(self):
        text = '"""Package docstring."""\n\n__all__ = ["Foo", "Bar"]\n'
        assert _is_trivial_init(text)

    def test_init_with_real_code_is_not_barrel(self):
        text = '"""Package docstring."""\n\nx = compute_something()\n'
        assert not _is_trivial_init(text)
        cat, source = classify_file_local_category(path="pkg/__init__.py", source_text=text, symbol_count=0, reexport_count=0)
        assert cat == "source"

    def test_symbols_present_is_never_barrel_even_with_reexports(self):
        cat, source = classify_file_local_category(
            path="src/thing.ts",
            source_text='export { helper } from "./helper";\nexport function real() { return 1; }\n',
            symbol_count=1, reexport_count=1,
        )
        assert cat != "barrel"


class TestPrecedence:
    def test_config_pattern_wins_over_barrel_shape(self):
        # A file that would otherwise qualify as barrel (no symbols, has a
        # re-export) but also matches a config filename pattern -- config wins.
        cat, source = classify_file_local_category(
            path="jest.config.js",
            source_text='export { base } from "./base.config";\n',
            symbol_count=0, reexport_count=1,
        )
        assert (cat, source) == ("config", "pattern")


class TestNeverReturnsEntry:
    def test_entry_is_never_a_file_local_result(self):
        # Even a file named exactly like a known entry-point basename --
        # entry detection is graph-dependent and lives only in ranking.py.
        cat, _ = classify_file_local_category(
            path="app/main.py", source_text="def main():\n    pass\n", symbol_count=1, reexport_count=0
        )
        assert cat != "entry"
        assert cat in ALL_CATEGORIES


class TestConfigLoading:
    def test_load_node_priors_has_all_categories(self):
        priors = load_node_priors()
        for cat in ALL_CATEGORIES:
            assert cat in priors["prior_values"], cat

    def test_entry_prior_value_is_1_4(self):
        # E4 landed: real config/code-pattern entry detection replaced the
        # untrustworthy graph-based heuristic, so the prior configured in
        # config/node_priors.yaml was bumped from 1.0 to 1.4 (see that
        # file's comment and DEFAULT_PRIOR_VALUES above).
        assert resolve_prior("entry") == 1.4

    def test_resolve_prior_unknown_category_defaults_to_1_0(self):
        assert resolve_prior("not_a_real_category", priors={"prior_values": {}}) == 1.0

    def test_missing_config_file_falls_back_to_defaults(self, monkeypatch):
        from app.core import config as config_module

        monkeypatch.setattr(config_module.settings, "NODE_PRIORS_PATH", "./nonexistent-priors.yaml")
        priors = load_node_priors()
        assert priors["prior_values"]["barrel"] == 0.4
