"""add content library: modules, topics, resources, roadmap library, progress

Revision ID: 2e631a0a0c04
Revises: 627b36d83e0a
Create Date: 2026-08-03 16:43:03.691251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2e631a0a0c04'
down_revision: Union[str, Sequence[str], None] = '627b36d83e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_roadmaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_roadmaps_slug'), ['slug'], unique=True)

    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modules_slug'), ['slug'], unique=True)

    op.create_table('resource_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_history_resource_id'), ['resource_id'], unique=False)

    op.create_table('module_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('module_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_assessments_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_assessments_user_id'), ['user_id'], unique=False)

    op.create_table('roadmap_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['content_roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmap_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_stages_roadmap_id'), ['roadmap_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'slug', name='uq_topic_module_slug')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_module_id'), ['module_id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('search_query', sa.String(length=255), nullable=True),
    sa.Column('source_hint', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_topic_id'), ['topic_id'], unique=False)

    op.create_table('roadmap_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('topics_generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['roadmap_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmap_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_nodes_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmap_nodes_stage_id'), ['stage_id'], unique=False)

    op.create_table('topic_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_topic_progress_user_topic')
    )
    with op.batch_alter_table('topic_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_progress_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
    # NOTE: autogenerate also detected pre-existing drift on interview_sessions,
    # node_content, roadmaps, and users (NOT NULL / missing index left over from
    # the old ad-hoc ALTER TABLE list in main.py). That's unrelated to the content
    # library and deliberately left out of this migration — see the Phase 1 report.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_topic_progress_topic_id'))

    op.drop_table('topic_progress')
    with op.batch_alter_table('roadmap_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_nodes_stage_id'))
        batch_op.drop_index(batch_op.f('ix_roadmap_nodes_module_id'))

    op.drop_table('roadmap_nodes')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_topic_id'))

    op.drop_table('resources')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_module_id'))

    op.drop_table('topics')
    with op.batch_alter_table('roadmap_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_stages_roadmap_id'))

    op.drop_table('roadmap_stages')
    with op.batch_alter_table('module_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_assessments_user_id'))
        batch_op.drop_index(batch_op.f('ix_module_assessments_module_id'))

    op.drop_table('module_assessments')
    with op.batch_alter_table('resource_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_history_resource_id'))

    op.drop_table('resource_history')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_slug'))

    op.drop_table('modules')
    with op.batch_alter_table('content_roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_roadmaps_slug'))

    op.drop_table('content_roadmaps')
    # ### end Alembic commands ###
