"""baseline: schema as of pre-content-library

Revision ID: 627b36d83e0a
Revises: 
Create Date: 2026-08-03 16:40:34.469943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627b36d83e0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=40), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_user_id'), ['user_id'], unique=False)

    op.create_table('communication_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('overall', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communication_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_sessions_modality'), ['modality'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('jd', sa.Text(), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=False),
    sa.Column('mcq', sa.JSON(), nullable=False),
    sa.Column('mcq_score', sa.Integer(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('node_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=40), nullable=False),
    sa.Column('briefing', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('eli5', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_content_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_content_roadmap_id'), ['roadmap_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_content_user_id'), ['user_id'], unique=False)

    op.create_table('resource_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_cache_slug'), ['slug'], unique=True)

    op.create_table('review_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=40), nullable=False),
    sa.Column('node_title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('interval_idx', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('last_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_items_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_items_user_id'), ['user_id'], unique=False)

    op.create_table('speech_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('target_secs', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speech_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speech_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=False),
    sa.Column('current_role', sa.String(length=120), nullable=False),
    sa.Column('target_role', sa.String(length=120), nullable=False),
    sa.Column('learning_goals', sa.Text(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('voice', sa.String(length=60), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('last_active', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vault_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vault_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vault_entries_user_id'), ['user_id'], unique=False)

    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('skills_gained', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missions_user_id'), ['user_id'], unique=False)

    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_role', sa.String(length=120), nullable=False),
    sa.Column('parent_roadmap_id', sa.Integer(), nullable=True),
    sa.Column('parent_node_id', sa.String(length=40), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmaps_parent_roadmap_id'), ['parent_roadmap_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmaps_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmaps_user_id'))
        batch_op.drop_index(batch_op.f('ix_roadmaps_parent_roadmap_id'))

    op.drop_table('roadmaps')
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missions_user_id'))

    op.drop_table('missions')
    with op.batch_alter_table('vault_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vault_entries_user_id'))

    op.drop_table('vault_entries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('speech_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speech_sessions_user_id'))

    op.drop_table('speech_sessions')
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_items_due_at'))

    op.drop_table('review_items')
    with op.batch_alter_table('resource_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_cache_slug'))

    op.drop_table('resource_cache')
    with op.batch_alter_table('node_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_content_user_id'))
        batch_op.drop_index(batch_op.f('ix_node_content_roadmap_id'))
        batch_op.drop_index(batch_op.f('ix_node_content_node_id'))

    op.drop_table('node_content')
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_sessions_user_id'))

    op.drop_table('interview_sessions')
    with op.batch_alter_table('communication_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_communication_sessions_modality'))

    op.drop_table('communication_sessions')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_user_id'))

    op.drop_table('assessments')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_user_id'))
        batch_op.drop_index(batch_op.f('ix_achievements_code'))

    op.drop_table('achievements')
    # ### end Alembic commands ###
